#!/bin/bash

DEVICE=$1
APP=$2

# Ensure not already connected
adb disconnect > /dev/null

# Initiate ADB connection to device
adb connect "$DEVICE":5555 > /dev/null

## APK BACKUP
printf "### APK BACKUP ###\n"

# Find the package name
PKG_NAME=$(adb shell pm list packages | grep "$2" | cut -d ':' -f2)
if [ -z $PKG_NAME ]; then
  echo "Could not find the package name: $2"
  adb disconnect > /dev/null
  exit 1
else
  echo "Package name is: $PKG_NAME"
fi

# Find the package path
while IFS= read -r -u10 VERSION
do
  if [ -z $VERSION ]; then
    echo "Could not find the path of: $PKG_NAME"
    adb disconnect > /dev/null
    exit 1
  else
    echo "The package path is: $VERSION"
  fi

  PKG_VER_NAME=$(basename "$VERSION")

  # Backup the apk
  printf "Backing up $VERSION to $(pwd)/backups/$PKG_NAME.$PKG_VER_NAME\n\n"
  sleep 3
  adb pull "$VERSION" backups/"$PKG_NAME.$PKG_VER_NAME"
  if [ $? -eq 0 ]; then
    echo "Success!"
    sleep 3
  else
    echo "Backup failed..."
    adb disconnect > /dev/null
    exit 1
  fi
done 10< <(adb shell pm path "$PKG_NAME" | cut -d ':' -f2)

## APP DATA BACKUP
printf "\n### APP DATA BACKUP ###\n"

# Backup the app data
echo "Backing up app data for $PKG_NAME to $(pwd)/backups/$PKG_NAME.ab"

printf "\n###########################################################\n"
printf "# YOU MAY GET A NOTICE ABOUT DEPRECATION AND/OR UNLOCKING #\n"
printf "# PLEASE IGNORE IT AND WAIT FOR THE OPERATION TO COMPLETE #\n"
printf "###########################################################\n"

sleep 5

# Run backup in separate process
adb backup -f backups/"$PKG_NAME".ab -apk -shared "$PKG_NAME" &
# Get backup PID
pid=$!
# Trap interrupt (ctrl+c) so we can stop the backup if script is stopped
trap "kill $pid" INT

echo "Data backup PID: $pid"
echo "Accepting backup..."

# Accept backup prompt, allowing for a short delay
sleep 1
adb shell input keyevent KEYCODE_TAB
adb shell input keyevent KEYCODE_TAB
# Sleep to allow for delay in keyboard to popping up
sleep 1
adb shell input keyevent KEYCODE_BACK
adb shell input keyevent KEYCODE_TAB
adb shell input keyevent KEYCODE_ENTER

# Wait for backup to complete
wait $pid
rc=$?

echo "Data backup complete. Exit code: $rc"

### This line must be replaced since the former `if [ $?..` is no longer relevant
if [ $rc -eq 0 ]; then
  echo "Success!"
else
  echo "App data backup failed..."
  adb disconnect > /dev/null
  exit 1
fi

# Disconnect adb
adb disconnect > /dev/null
