#!/bin/bash

DEVICE=$1
APP=$2

# Ensure not already connected
adb disconnect > /dev/null

# Initiate ADB connection to device
adb connect "$DEVICE":5555 > /dev/null

## APK RESTORE
printf "### APK RESTORE ###\n"
adb install "$APP".apk

## APP DATA RESTORE
printf "### APP DATA RESTORE ###\n"
adb restore "$APP".ab

# Disconnect adb
adb disconnect > /dev/null
